<?php

declare(strict_types=1);

namespace PHPSTORM_META;

expectedArguments(
    \sentrion(),
    0,
    'assets',
    'charts',
    'controllers',
    'db',
    'entities',
    'grids',
    'helpers',
    'ip',
    'ips',
    'log',
    'models',
    'page',
    'pages',
    'request',
    'resource',
    'resources',
    'response',
    'router',
    'rule',
    'rules',
    'session',
    'storage',
    'sysop',
    'user',
    'users',
    'utils',
);

override(\sentrion(), map([
    'assets'    => \Sentrion\Core\Services\Assets::class,
    'charts'    => \Sentrion\Core\Services\Charts::class,
    'controllers' => \Sentrion\Core\Services\Controllers::class,
    'db'        => \Sentrion\Core\Services\Db::class,
    'entities'  => \Sentrion\Core\Services\Entities::class,
    'grids'     => \Sentrion\Core\Services\Grids::class,
    'helpers'   => \Sentrion\Core\Services\Helpers::class,
    'ip'        => \Sentrion\Core\Services\Ip::class,
    'ips'       => \Sentrion\Core\Services\Ips::class,
    'log'       => \Sentrion\Core\Services\Log::class,
    'models'    => \Sentrion\Core\Services\Models::class,
    'page'      => \Sentrion\Core\Services\Page::class,
    'pages'     => \Sentrion\Core\Services\Pages::class,
    'request'   => \Sentrion\Core\Services\Request::class,
    'resource'  => \Sentrion\Core\Services\Resource::class,
    'resources' => \Sentrion\Core\Services\Resources::class,
    'response'  => \Sentrion\Core\Services\Response::class,
    'router'    => \Sentrion\Core\Services\Router::class,
    'rule'      => \Sentrion\Core\Services\Rule::class,
    'rules'     => \Sentrion\Core\Services\Rules::class,
    'session'   => \Sentrion\Core\Services\Session::class,
    'storage'   => \Sentrion\Core\Services\Storage::class,
    'sysop'     => \Sentrion\Core\Services\Sysop::class,
    'user'      => \Sentrion\Core\Services\User::class,
    'users'     => \Sentrion\Core\Services\Users::class,
    'utils'     => \Sentrion\Core\Services\Utils::class,
    '' => '@',
]));
