[routes]

;ajax section start
PUT /saveRule            [ajax] = \Sentrion\Controllers\Data->saveRule
PUT /removeBlacklisted   [ajax] = \Sentrion\Controllers\Data->removeFromBlacklist
PUT /removeWatchlisted   [ajax] = \Sentrion\Controllers\Data->removeFromWatchlist
PUT /manageUser          [ajax] = \Sentrion\Controllers\Data->manageUser
PUT /reviewUser          [ajax] = \Sentrion\Controllers\Data->reviewUser
PUT /emailReenrichment   [ajax] = \Sentrion\Controllers\Data->enrichEmailEntity
PUT /phoneReenrichment   [ajax] = \Sentrion\Controllers\Data->enrichPhoneEntity

POST|GET /loadTopTen      [ajax] = \Sentrion\Controllers\Data->getTopTen

GET /currentTime          [ajax] = \Sentrion\Controllers\Data->getCurrentTime
GET /getConstants         [ajax] = \Sentrion\Controllers\Data->getConstants

GET /search               [ajax] = \Sentrion\Controllers\Data->getSearchResults
GET /checkRule            [ajax] = \Sentrion\Controllers\Data->checkRule
GET /scoreDetails         [ajax] = \Sentrion\Controllers\Data->getUserScoreDetails
GET /loadDashboardStat    [ajax] = \Sentrion\Controllers\Data->getDashboardStat
GET /loadMap              [ajax] = \Sentrion\Controllers\Data->getMap
GET /loadReviewQueueCount [ajax] = \Sentrion\Controllers\Data->getReviewUsersQueueCount
GET /loadBlacklistCount   [ajax] = \Sentrion\Controllers\Data->getBlacklistUsersCount
GET /timeFrameTotal       [ajax] = \Sentrion\Controllers\Data->getTimeFrameTotal

;panel
GET /emailDetails         [ajax] = \Sentrion\Controllers\Data->getEmailDetails
GET /eventDetails         [ajax] = \Sentrion\Controllers\Data->getEventDetails
GET /fieldEventDetails    [ajax] = \Sentrion\Controllers\Data->getFieldEventDetails
GET /phoneDetails         [ajax] = \Sentrion\Controllers\Data->getPhoneDetails
GET /deviceDetails        [ajax] = \Sentrion\Controllers\Data->getDeviceDetails
GET /logbookDetails       [ajax] = \Sentrion\Controllers\Data->getLogbookDetails

GET /enrichmentDetails    [ajax] = \Sentrion\Controllers\Data->getNotCheckedEntitiesCount

;tile details
GET /loadDomainDetails            [ajax] = \Sentrion\Controllers\Data->getDomainDetails
GET /loadUserAgentDetails         [ajax] = \Sentrion\Controllers\Data->getUserAgentDetails
GET /loadIspDetails               [ajax] = \Sentrion\Controllers\Data->getIspDetails
GET /loadUserDetails              [ajax] = \Sentrion\Controllers\Data->getUserDetails
GET /loadIpDetails                [ajax] = \Sentrion\Controllers\Data->getIpDetails

;tables
POST|GET /loadEvents           [ajax] = \Sentrion\Controllers\Data->getEventsList
POST|GET /loadUsers            [ajax] = \Sentrion\Controllers\Data->getUsersList
POST|GET /loadReviewQueue      [ajax] = \Sentrion\Controllers\Data->getReviewQueueList
POST|GET /loadBlacklist        [ajax] = \Sentrion\Controllers\Data->getBlacklistList
POST|GET /loadDevices          [ajax] = \Sentrion\Controllers\Data->getDevicesList
POST|GET /loadUserAgents       [ajax] = \Sentrion\Controllers\Data->getUserAgentsList
POST|GET /loadResources        [ajax] = \Sentrion\Controllers\Data->getResourcesList
POST|GET /loadPhones           [ajax] = \Sentrion\Controllers\Data->getPhonesList
POST|GET /loadFieldAuditTrail  [ajax] = \Sentrion\Controllers\Data->getFieldAuditTrailList
POST|GET /loadFieldAudits      [ajax] = \Sentrion\Controllers\Data->getFieldAuditsList
POST|GET /loadIsps             [ajax] = \Sentrion\Controllers\Data->getIspsList
POST|GET /loadIps              [ajax] = \Sentrion\Controllers\Data->getIpsList
POST|GET /loadEmails           [ajax] = \Sentrion\Controllers\Data->getEmailsList
POST|GET /loadDomains          [ajax] = \Sentrion\Controllers\Data->getDomainsList
POST|GET /loadLogbook          [ajax] = \Sentrion\Controllers\Data->getLogbookList
POST|GET /loadUsageStats       [ajax] = \Sentrion\Controllers\Data->getUsageStats
POST|GET /loadCountries        [ajax] = \Sentrion\Controllers\Data->getCountriesList
POST|GET /loadRules            [ajax] = \Sentrion\Controllers\Data->getRulesList

;totals
GET /loadIpsTimeFrameTotal         [ajax] = \Sentrion\Controllers\Data->getIpsTimeFrameTotal
GET /loadIspsTimeFrameTotal        [ajax] = \Sentrion\Controllers\Data->getIspsTimeFrameTotal
GET /loadDomainsTimeFrameTotal     [ajax] = \Sentrion\Controllers\Data->getDomainsTimeFrameTotal
GET /loadCountriesTimeFrameTotal   [ajax] = \Sentrion\Controllers\Data->getCountriesTimeFrameTotal
GET /loadResourcesTimeFrameTotal   [ajax] = \Sentrion\Controllers\Data->getResourcesTimeFrameTotal
GET /loadFieldAuditsTimeFrameTotal [ajax] = \Sentrion\Controllers\Data->getFieldAuditsTimeFrameTotal
GET /loadUserAgentsTimeFrameTotal  [ajax] = \Sentrion\Controllers\Data->getUserAgentsTimeFrameTotal

;charts
GET /loadEventsChart           [ajax] = \Sentrion\Controllers\Data->getEventsChart
GET /loadUsersChart            [ajax] = \Sentrion\Controllers\Data->getUsersChart
GET /loadReviewQueueChart      [ajax] = \Sentrion\Controllers\Data->getReviewQueueChart
GET /loadBlacklistChart        [ajax] = \Sentrion\Controllers\Data->getBlacklistChart
GET /loadDevicesChart          [ajax] = \Sentrion\Controllers\Data->getDevicesChart
GET /loadUserAgentsChart       [ajax] = \Sentrion\Controllers\Data->getUserAgentsChart
GET /loadResourcesChart        [ajax] = \Sentrion\Controllers\Data->getResourcesChart
GET /loadPhonesChart           [ajax] = \Sentrion\Controllers\Data->getPhonesChart
GET /loadFieldAuditTrailChart  [ajax] = \Sentrion\Controllers\Data->getFieldAuditTrailChart
GET /loadFieldAuditsChart      [ajax] = \Sentrion\Controllers\Data->getFieldAuditsChart
GET /loadIspsChart             [ajax] = \Sentrion\Controllers\Data->getIspsChart
GET /loadIpsChart              [ajax] = \Sentrion\Controllers\Data->getIpsChart
GET /loadDomainsChart          [ajax] = \Sentrion\Controllers\Data->getDomainsChart
GET /loadLogbookChart          [ajax] = \Sentrion\Controllers\Data->getLogbookChart
GET /loadUserSparklinesChart   [ajax] = \Sentrion\Controllers\Data->getUserSparklinesChart

;ajax section end

;pages section start
POST|GET /signup                        = \Sentrion\Controllers\Navigation->getSignupPage
POST|GET /login                         = \Sentrion\Controllers\Navigation->getLoginPage
POST|GET @logout: /logout               = \Sentrion\Controllers\Navigation->getLogoutPage
POST|GET /forgot-password               = \Sentrion\Controllers\Navigation->getForgotPasswordPage
POST|GET /password-recovering/@renewKey = \Sentrion\Controllers\Navigation->getPasswordRecoveringPage

GET /                                   = \Sentrion\Controllers\Navigation->getHomePage
GET /event                              = \Sentrion\Controllers\Navigation->getEventsPage
GET /review-queue                       = \Sentrion\Controllers\Navigation->getReviewQueuePage
GET /blacklist                          = \Sentrion\Controllers\Navigation->getBlacklistPage
GET /logbook                            = \Sentrion\Controllers\Navigation->getLogbookPage
GET /watchlist                          = \Sentrion\Controllers\Navigation->getWatchlistPage

POST|GET @api: /api                     = \Sentrion\Controllers\Navigation->getApiPage
POST|GET @rules: /rules                 = \Sentrion\Controllers\Navigation->getRulesPage
POST|GET @settings: /settings           = \Sentrion\Controllers\Navigation->getSettingsPage
POST|GET @manualCheck: /manual-check    = \Sentrion\Controllers\Navigation->getManualCheckPage

;pages with reenrichment
POST|GET /id/@userId                    = \Sentrion\Controllers\Navigation->getUserPage
POST|GET /user-agent/@userAgentId       = \Sentrion\Controllers\Navigation->getUserAgentPage
POST|GET /ip/@ipId                      = \Sentrion\Controllers\Navigation->getIpPage
POST|GET /domain/@domainId              = \Sentrion\Controllers\Navigation->getDomainPage

GET /id                         = \Sentrion\Controllers\Navigation->getUsersPage
GET /user-agent                 = \Sentrion\Controllers\Navigation->getUserAgentsPage
GET /ip                         = \Sentrion\Controllers\Navigation->getIpsPage
GET /isp                        = \Sentrion\Controllers\Navigation->getIspsPage
GET /isp/@ispId                 = \Sentrion\Controllers\Navigation->getIspPage
GET /country                    = \Sentrion\Controllers\Navigation->getCountriesPage
GET /country/@countryId         = \Sentrion\Controllers\Navigation->getCountryPage
GET /domain                     = \Sentrion\Controllers\Navigation->getDomainsPage
GET /resource                   = \Sentrion\Controllers\Navigation->getResourcesPage
GET /resource/@resourceId       = \Sentrion\Controllers\Navigation->getResourcePage
GET /field                      = \Sentrion\Controllers\Navigation->getFieldAuditsPage
GET /field/@fieldId             = \Sentrion\Controllers\Navigation->getFieldAuditPage

;pages section end

GET /cron [cli] = \Sentrion\Controllers\Pages\Cron->index
